### ISSUE TITLE
Testing on DAVIS gives error from rawframe_dataset.py

### ISSUE THREAD

**Issue by gurdeepmaurya** [xvjiarui/VFS#5]
Hi,

I'm getting error from rawframe_dataset.py. 
# Platform
Testing this on Google Colab pro VM High RAM (25GB), P100 GPU.
Pytorch 1.9.0
cuda 11.1
python 3.7.12
torchvision 0.10.0
# Script

`!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`

`!pip install git+https://github.com/xvjiarui/davis2017-evaluation`

`!pip install got10k`

`!git clone https://github.com/xvjiarui/VFS/`
`!mv VFS/* ./`
`!pip install -e .`
`!wget https://data.vision.ee.ethz.ch/csergi/share/davis/DAVIS-2017-trainval-480p.zip`
`!mkdir ./data`
`!mkdir ./data/davis`
`!unzip -q DAVIS-2017-trainval-480p.zip -d ./data/davis/`
`!wget https://github.com/xvjiarui/VFS/releases/download/v0.1-rc1/davis2017_val_list_rawframes.txt -o ./data/davis/DAVIS/ImageSets/davis2017_val_list_rawframes.txt`

`!./tools/dist_test.sh configs/r18_nc_sgd_cos_100e_r2_1xNx8_k400.py https://github.com/xvjiarui/VFS/releases/download/v0.1-rc1/r18_nc_sgd_cos_100e_r2_1xNx8_k400-db1a4c0d.pth 1  --eval davis --options test_cfg.save_np=True`

Following are the details of error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/content/mmaction/datasets/davis_dataset.py", line 53, in __init__
    modality='RGB')
  File "/content/mmaction/datasets/rawframe_dataset.py", line 93, in __init__
    multi_class, num_classes, start_index, modality)
  File "/content/mmaction/datasets/base.py", line 67, in __init__
    self.video_infos = self.load_annotations()
  File "/content/mmaction/datasets/rawframe_dataset.py", line 118, in load_annotations
    video_info['total_frames'] = int(line_split[idx])
ValueError: invalid literal for int() with base 10: '06:58:52--'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 166, in <module>
    main()
  File "./tools/test.py", line 120, in main
    dataset = build_dataset(cfg.data.test, dict(test_mode=True))
  File "/content/mmaction/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')

**Comment by xvjiarui** [comment]
Hi @gurdeepmaurya 
I am not sure about the reason. 
I tried from my side and it works. 
Could you please check what is `line_split[idx]` in L118 in ` /content/mmaction/datasets/rawframe_dataset.py`?

**Comment by gurdeepmaurya** [comment]
Hi xvjiarui,
I inserted 
`print(f"AKSHIT DEBUG PRINT, \nType:{type(line_split[idx])}\nValue:{line_split[idx]}")`

at L118 of `/content/mmaction/datasets/rawframe_dataset.py`

Got this in the output:

AKSHIT DEBUG PRINT, 
Type:<class 'str'>
Value:12:18:34--
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/content/mmaction/datasets/davis_dataset.py", line 53, in __init__
    modality='RGB')
  File "/content/mmaction/datasets/rawframe_dataset.py", line 93, in __init__
    multi_class, num_classes, start_index, modality)
  File "/content/mmaction/datasets/base.py", line 67, in __init__
    self.video_infos = self.load_annotations()
  File "/content/mmaction/datasets/rawframe_dataset.py", line 119, in load_annotations
    video_info['total_frames'] = int(line_split[idx])
ValueError: invalid literal for int() with base 10: '12:18:34--'


Sorry for the delayed response, Got called back to campus and there was a covid situation.
Let me know what else you need. I'd recommend you run the script in Colab Pro's instance (possibly after Christmas),
It's easily reproducible.

Merry Christmas!!

**Comment by xvjiarui** [comment]
Hi @gurdeepmaurya 

I think your dataset file structure may not be correct. Please check https://github.com/xvjiarui/VFS#data-preparation for the file structure.

**Comment by xvjiarui** [comment]
Please feel free to re-open this issue if there is still an issue.
