### ISSUE TITLE
ModuleNotFoundError: No module named 'mmaction.version'

### ISSUE THREAD

**Issue by hamidehkerdegari** [xvjiarui/VFS#7]
Hi,
I am trying to run pretraining through "./tools/dist_train.sh ${CONFIG} ${GPUS}", however I get the following error:

Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from mmaction import __version__
  File "/home/hk20/VFS/mmaction/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmaction.version'
Killing subprocess 1976193
Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hk20/anaconda3/envs/vfs/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/r18_nc_sgd_cos_100e_r2_1xNx8_k400.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

Any idea how to solve this issue?

**Comment by xvjiarui** [comment]
Hi @hamidehkerdegari 
You may need to run `pip install -e .` under the folder for the repo.

**Comment by hamidehkerdegari** [comment]
Many Thanks @xvjiarui.
The issue was solved, now I got another error which seems to be related to load_json_annotations() function when tries to read the json annotation for kinetics dataset:

Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/hk20/VFS/mmaction/datasets/video_dataset.py", line 43, in __init__
    super().__init__(ann_file, pipeline, start_index=start_index, **kwargs)
  File "/home/hk20/VFS/mmaction/datasets/base.py", line 67, in __init__
    self.video_infos = self.load_annotations()
  File "/home/hk20/VFS/mmaction/datasets/video_dataset.py", line 48, in load_annotations
    return self.load_json_annotations()
  File "/home/hk20/VFS/mmaction/datasets/base.py", line 80, in load_json_annotations
    path_key = 'frame_dir' if 'frame_dir' in dict(video_infos[0]) else 'filename'
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 181, in <module>
    main()
  File "./tools/train.py", line 156, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/hk20/VFS/mmaction/datasets/builder.py", line 37, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/hk20/VFS/mmaction/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'VideoDataset: 0'
Killing subprocess 1982076
Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hk20/anaconda3/envs/vfs/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/r18_nc_sgd_cos_100e_r2_1xNx8_k400.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

The code assumes that video_infos to be a list I guess...
