### ISSUE TITLE
Issues relating to using ann_file_train for Kinetics400 dataset

### ISSUE THREAD

**Issue by hamidehkerdegari** [xvjiarui/VFS#8]
Hi,

When I train the model, I face the following issues either use "kinetics400_train_list_videos.txt" or "kinetics400_train_list_videos.js
on" :
**1)txt file error:**
Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/hk20/VFS/mmaction/datasets/video_dataset.py", line 43, in __init__
    super().__init__(ann_file, pipeline, start_index=start_index, **kwargs)
  File "/home/hk20/VFS/mmaction/datasets/base.py", line 67, in __init__
    self.video_infos = self.load_annotations()
  File "/home/hk20/VFS/mmaction/datasets/video_dataset.py", line 61, in load_annotations
    filename, label = line_split
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 181, in <module>
    main()
  File "./tools/train.py", line 156, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/hk20/VFS/mmaction/datasets/builder.py", line 37, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/hk20/VFS/mmaction/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: VideoDataset: not enough values to unpack (expected 2, got 1)
Killing subprocess 2017741
Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hk20/anaconda3/envs/vfs/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/r18_nc_sgd_cos_100e_r2_1xNx8_k400.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**2)json file error**
Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/hk20/VFS/mmaction/datasets/video_dataset.py", line 43, in __init__
    super().__init__(ann_file, pipeline, start_index=start_index, **kwargs)
  File "/home/hk20/VFS/mmaction/datasets/base.py", line 67, in __init__
    self.video_infos = self.load_annotations()
  File "/home/hk20/VFS/mmaction/datasets/video_dataset.py", line 48, in load_annotations
    return self.load_json_annotations()
  File "/home/hk20/VFS/mmaction/datasets/base.py", line 80, in load_json_annotations
    path_key = 'frame_dir' if 'frame_dir' in video_infos[0] else 'filename'
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 181, in <module>
    main()
  File "./tools/train.py", line 156, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/hk20/VFS/mmaction/datasets/builder.py", line 37, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/hk20/VFS/mmaction/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'VideoDataset: 0'
Killing subprocess 2017835
Traceback (most recent call last):
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/hk20/anaconda3/envs/vfs/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hk20/anaconda3/envs/vfs/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/r18_nc_sgd_cos_100e_r2_1xNx8_k400.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

I also attached the txt file that I am using, any idea how to solve this issue?
[kinetics400_train_list_videos.txt](https://github.com/xvjiarui/VFS/files/7441097/kinetics400_train_list_videos.txt)

**Comment by xvjiarui** [comment]
Hi @hamidehkerdegari 
I have attached my file for your reference
[kinetics400_train_list_videos.txt](https://github.com/xvjiarui/VFS/files/7447736/kinetics400_train_list_videos.txt)
.

**Comment by hamidehkerdegari** [comment]
Thanks @xvjiarui. This solved my issue.
